package com.fiesta.domain;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.math.BigDecimal;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles("test")
class LoanApplicationTest {

    @Autowired
    private TestEntityManager entityManager;

    @Test
    void shouldPopulateDefaultsOnPersist() {
        // Given
        LoanApplication application = new LoanApplication();
        application.setApplicantId("app-123");
        application.setAmount(new BigDecimal("10000.00"));
        application.setTermMonths(24);

        // Verify pre-persist state
        assertThat(application.getId()).isNull();
        assertThat(application.getCreatedAt()).isNull();
        assertThat(application.getStatus()).isNull();

        // When
        LoanApplication savedApplication = entityManager.persistFlushFind(application);

        // Then
        assertThat(savedApplication.getId()).isNotNull();
        assertThat(savedApplication.getCreatedAt()).isNotNull();
        assertThat(savedApplication.getStatus()).isEqualTo("PENDING_REVIEW");
    }

    @Test
    void shouldVerifyLombokGeneratedMethods() {
        // Given
        UUID id = UUID.randomUUID();
        String applicantId = "applicant-456";
        BigDecimal amount = new BigDecimal("5000.50");
        Integer termMonths = 12;

        // When
        LoanApplication application = new LoanApplication();
        application.setId(id);
        application.setApplicantId(applicantId);
        application.setAmount(amount);
        application.setTermMonths(termMonths);

        // Then
        assertThat(application.getId()).isEqualTo(id);
        assertThat(application.getApplicantId()).isEqualTo(applicantId);
        assertThat(application.getAmount()).isEqualTo(amount);
        assertThat(application.getTermMonths()).isEqualTo(termMonths);

        // Test toString (generated by @Data)
        String toString = application.toString();
        assertThat(toString).contains("LoanApplication(id=" + id);
        assertThat(toString).contains("applicantId=" + applicantId);

        // Test equals and hashCode (generated by @Data)
        LoanApplication sameApplication = new LoanApplication();
        sameApplication.setId(id);
        sameApplication.setApplicantId(applicantId);
        sameApplication.setAmount(amount);
        sameApplication.setTermMonths(termMonths);

        assertThat(application).isEqualTo(sameApplication);
        assertThat(application.hashCode()).isEqualTo(sameApplication.hashCode());
    }
}
